# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/ruby/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ruby)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,69e8b84aa220db64bf6e0b969d3800abf9ed5645)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,2615b7783869d6419c59e7622bcb8208863b15f8)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,04c9167197ac9429a8877075619c6ad99b2222e8)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,e7158649606ee7441d6534728af31d3752539eb9)
$(call add-radio-file-sha1-checked,radio/dpm.img,e9a2e4fcb343010b299a934d37d4186f59a07d7d)
$(call add-radio-file-sha1-checked,radio/gz.img,5b3cc44a66e8e121cc7317d08bc101550dd71ef0)
$(call add-radio-file-sha1-checked,radio/lk.img,2305a6ff184b1236f79c8d5955defa8d7c137f21)
$(call add-radio-file-sha1-checked,radio/logo.img,a82f9fdebbf00ec7526a831e57c36b6dc3ffcc65)
$(call add-radio-file-sha1-checked,radio/mcupm.img,48695b570c5265ae5d086603f23e6ba3a281aced)
$(call add-radio-file-sha1-checked,radio/md1img.img,be9cb02c211219bfb8b1a715db4c6811fab51edc)
$(call add-radio-file-sha1-checked,radio/pi_img.img,6c2ecceb56ea15cb3629525457331aca13e8ae48)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,81f3f5508bd4b61aade845b1c4145d06f0954097)
$(call add-radio-file-sha1-checked,radio/scp.img,bb882416ef49538725739156e6714ecd900943f7)
$(call add-radio-file-sha1-checked,radio/spmfw.img,8c05a988d81aaace477738ed958fc7b5498d3ca7)
$(call add-radio-file-sha1-checked,radio/sspm.img,7671769e855827b875b2a916b9217654436fa4b3)
$(call add-radio-file-sha1-checked,radio/tee.img,407d24f6e597181ee1c1bebf4897a95684505507)

endif
